version: "3.9"

services:
################################
#   Setup Vue app container
################################
  web:
    build: ./client
    ports:
      - "3500:3500"
    volumes:
      - ./client:/app
    links: 
      - "redis"
      - "server"

################################
#   Setup REDIS Server container
################################
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ${PWD}/dump.rdb:/dump.rdb:rw
################################
#   Setup Nodejs Server container
################################
  server:
    build: ./server
    ports:
      - "3600:3600"
    depends_on: 
      - redis
    environment:
      - REDIS_SERVER=redis
    volumes:
      - ./server:/home/app
      - /home/app/node_modules
################################
#   Setup nginx load balancer
################################
  nginx:
    image: nginx:latest # this will use the latest version of 1.13.x
    ports:
      - '80:80' # expose 80 on host and sent to 80 in container
    depends_on: 
      - web
      - server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
volumes:  
  redis_data:
